# Generated by Django 4.1.1 on 2022-10-03 22:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+19993335577', max_length=128, null=True, region=None, unique=True),
        ),
    ]
