# Generated by Django 4.1 on 2022-09-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_qa_publish_alter_qa_created_alter_qa_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifest',
            options={'verbose_name': 'Who are we?', 'verbose_name_plural': 'Who are we?'},
        ),
    ]
