# Generated by Django 4.1 on 2022-09-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_manifest_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
