# Generated by Django 4.1.1 on 2022-10-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create'),
        ),
        migrations.AddField(
            model_name='news',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Edit'),
        ),
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
