# Generated by Django 4.1.1 on 2022-10-15 03:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create')),
                ('edited', models.DateTimeField(auto_now=True, null=True, verbose_name='Edit')),
                ('tag', models.ManyToManyField(to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
