# Generated by Django 4.1.1 on 2022-10-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
