# Generated by Django 4.1.1 on 2022-10-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_news_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Post',
        ),
    ]
