# Generated by Django 4.1.1 on 2022-10-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
