# Generated by Django 4.1.1 on 2022-10-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_category_options_post_category_alter_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='You pick only 1 category', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
