# Generated by Django 4.1 on 2022-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='hash',
            field=models.CharField(default=0, max_length=1000, verbose_name='Transaction HASH or TXID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deposit',
            name='is_decline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='hash',
            field=models.CharField(blank=True, help_text='ID of transaction of money to the user', max_length=1000, null=True, verbose_name='Transaction HASH or TXID'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Everything is ok and payed'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='is_decline',
            field=models.BooleanField(default=False, help_text='cant pay'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='wallet_id',
            field=models.CharField(default=0, help_text='Wallet ID of user', max_length=1000, verbose_name='Wallet Address'),
            preserve_default=False,
        ),
    ]
