# Generated by Django 4.1 on 2022-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_deposit_date_deposit_hash_deposit_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='hash',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Transaction HASH or TXID'),
        ),
    ]
