# Generated by Django 4.1 on 2022-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_deposit_date_deposit_is_approved_withdraw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
