# Generated by Django 4.1 on 2022-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_withdraw_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
