# Generated by Django 4.1 on 2022-08-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_withdraw_is_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Everything is ok for payment'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='is_payed',
            field=models.BooleanField(default=False, help_text='Money transfer is done'),
        ),
    ]
