# Generated by Django 4.1 on 2022-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_withdraw_is_approved_alter_withdraw_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='hash',
            field=models.TextField(default=0, max_length=10000, verbose_name='Transaction HASH or TXID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='hash',
            field=models.TextField(default=0, max_length=10000, verbose_name='Transaction HASH or TXID'),
            preserve_default=False,
        ),
    ]
