# Generated by Django 4.1 on 2022-08-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_deposit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_decline',
            field=models.BooleanField(default=False),
        ),
    ]
