# Generated by Django 4.1 on 2022-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_withdraw_wallet_id_alter_withdraw_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='hash',
            field=models.CharField(blank=True, help_text='ID of transaction of money to the user', max_length=1000, null=True, verbose_name='Transaction HASH or TXID'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='wallet_id',
            field=models.CharField(help_text='Wallet ID of user', max_length=1000, verbose_name='Wallet Address'),
        ),
    ]
