# Generated by Django 4.1 on 2022-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_alter_withdraw_hash_alter_withdraw_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='is_decline',
            field=models.BooleanField(default=False, help_text='cant pay'),
        ),
    ]
