# Generated by Django 4.1 on 2022-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_withdraw_is_decline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='is_payed',
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Everything is ok and payed'),
        ),
    ]
