# Generated by Django 4.1 on 2022-08-12 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='Access Token')),
                ('is_used', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('representative', models.ForeignKey(help_text='every user has 3 of this code as representative', on_delete=django.db.models.deletion.CASCADE, related_name='representative_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='belongs to 3 different user', on_delete=django.db.models.deletion.CASCADE, related_name='test_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
