# Generated by Django 4.1 on 2022-08-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
    ]
