# Generated by Django 4.1 on 2022-08-12 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_token', '0002_remove_accesstoken_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='representative',
            field=models.ForeignKey(default=1, help_text='every user has 3 of this code as representative', on_delete=django.db.models.deletion.CASCADE, related_name='representative_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
