# Generated by Django 4.1 on 2022-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0005_alter_accesstoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(default=1, max_length=128, verbose_name='Access Token'),
            preserve_default=False,
        ),
    ]
