# Generated by Django 4.1 on 2022-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0007_alter_accesstoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='by_superuser',
            field=models.BooleanField(default=False, verbose_name='Create by superuser manually'),
        ),
    ]
