# Generated by Django 4.1 on 2022-08-15 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_token', '0008_accesstoken_by_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='by_superuser',
            field=models.BooleanField(default=False, help_text='Super user Created this Accesses token manually', verbose_name='Create by admin'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='is_used',
            field=models.BooleanField(default=False, help_text='a user registered with this token'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='representative',
            field=models.ForeignKey(help_text='That user whom created this after deposit confirm', on_delete=django.db.models.deletion.CASCADE, related_name='representative_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user registered with this token', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
