# Generated by Django 4.1.1 on 2022-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0009_alter_accesstoken_by_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.CharField(help_text='unique number who belongs to one person', max_length=128, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='by_superuser',
            field=models.BooleanField(default=False, help_text='Admin (superuser) Created this token manually', verbose_name='Create by admin'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='is_used',
            field=models.BooleanField(default=False, help_text='user used this token to register'),
        ),
    ]
